server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index home.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location = /cart {
        try_files /products_olsPage_cart.html =404;
    }
}