services:
  builder:
    build:
      context: ./app
    volumes:
      - build_files:/app/dist
    command: ["true"]

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - build_files:/usr/share/nginx/html/dist
    depends_on:
      - builder

  express:
    build: 
      context: ./express
    expose:
      - "3000"
    depends_on:
      - builder
    # volumes:
    #   - build_files:/app/dist
volumes:
  build_files:
