services:
  builder:
    build:
      context: ./app
    volumes:
      - build_server:/app/dist/server
    command: ["true"]

  nginx:
    build:
      context: ./client
    ports:
      - "8080:80"
    depends_on:
      - builder

  server:
    build: 
      context: ./server
    volumes:
      - build_server:/app/public:ro
    ports:
      - "3000:3000"
    depends_on:
      - builder

volumes:
  build_server:
